{"name": "test_fail1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail1():\n>       assert False\nE       assert False\n\ntest_fail.py:2: AssertionError"}, "start": 1747922923482, "stop": 1747922923482, "uuid": "185829fe-f8ac-4aca-a5c4-26577541ca69", "historyId": "5980a0f138d2262d80936b48f834090e", "testCaseId": "5980a0f138d2262d80936b48f834090e", "fullName": "tests.simple.test_fail#test_fail1", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "18636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}