{"name": "test_fail6", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail6():\n>       assert False\nE       assert False\n\ntest_fail.py:17: AssertionError"}, "start": 1747924468625, "stop": 1747924468625, "uuid": "a0739fba-4095-4a7b-8807-4cf3bb37372d", "historyId": "9ebd70578965c6a6474c5346ee5a0af2", "testCaseId": "9ebd70578965c6a6474c5346ee5a0af2", "fullName": "tests.simple.test_fail#test_fail6", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Pro-Nikita.local"}, {"name": "thread", "value": "20048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}